services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "8080:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=metabasepassword
      - MB_DB_HOST=postgres
    depends_on:
      - postgres
    volumes:
      - ./plugins:/plugins

  postgres:
    image: postgres:13
    container_name: metabase-postgres
    environment:
      - POSTGRES_DB=metabase
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=metabasepassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
